#ifndef CONSTANTS_H
#define CONSTANTS_H

#define APPRETURN_SETTINGS  101
#define APPRETURN_LOGIN     102
#define APPRETURN_WELCOME   103
#define APPRETURN_MUI_SETTINGS 104
#define APPRETURN_SAVE_SETTINGS 105
#define APPRETURN_DO_LOGIN 106
#define APPRETURN_POST 107
#define APPRETURN_TEXT_CHANGED 108

#define APPRETURN_REFRESH_TIMELINE 200
#define APPRETURN_TIMELINE_SELECT 201
#define APPRETURN_NAVIGATION 202
#define APPRETURN_REFRESH_NOTIFICATIONS 203
#define APPRETURN_NOTIFICATION_SELECT 204
#define APPRETURN_REFRESH_FAVOURITES 205
#define APPRETURN_FAVOURITES_SELECT 206
#define APPRETURN_REFRESH_BOOKMARKS 207
#define APPRETURN_BOOKMARKS_SELECT 208
#define APPRETURN_FAVOURITE_TOOT 209
#define APPRETURN_BOOST_TOOT 210

#endif
