#ifndef CONSTANTS_H
#define CONSTANTS_H

#define APPRETURN_SETTINGS  101
#define APPRETURN_LOGIN     102
#define APPRETURN_WELCOME   103
#define APPRETURN_MUI_SETTINGS 104
#define APPRETURN_SAVE_SETTINGS 105
#define APPRETURN_REFRESH_TIMELINE 1035
#define APPRETURN_DO_LOGIN      106

#endif
